// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Orfelin.Core.Data;

#nullable disable

namespace Orfelin.API.Migrations
{
    [DbContext(typeof(OrfelinContext))]
    [Migration("20260611123433_DodavanjeRootKorisnika")]
    partial class DodavanjeRootKorisnika
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Orfelin.Core.Models.Knjiga", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Autor")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("BrojStrana")
                        .HasColumnType("int");

                    b.Property<DateTime>("DatumNabavke")
                        .HasColumnType("datetime2");

                    b.Property<int>("DostupnoKopija")
                        .HasColumnType("int");

                    b.Property<int>("GodinaIzdavanja")
                        .HasColumnType("int");

                    b.Property<string>("ISBN")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("InventarniBroj")
                        .HasColumnType("int");

                    b.Property<string>("Izdavac")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Naslov")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UkupanBrojKopija")
                        .HasColumnType("int");

                    b.Property<DateTime?>("VremeIzmene")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("VremeKreiranja")
                        .HasColumnType("datetime2");

                    b.Property<string>("Zanr")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Knjige");
                });

            modelBuilder.Entity("Orfelin.Core.Models.Korisnik", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Aktivan")
                        .HasColumnType("bit");

                    b.Property<string>("BrojClanskeKarte")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DatumClanstva")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ime")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Prezime")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("VremeIzmene")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("VremeKreiranja")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Korisnici");
                });

            modelBuilder.Entity("Orfelin.Core.Models.Pozajmica", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DatumPozajmice")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DatumVracanja")
                        .HasColumnType("datetime2");

                    b.Property<int>("KnjigaId")
                        .HasColumnType("int");

                    b.Property<int>("KorisnikId")
                        .HasColumnType("int");

                    b.Property<DateTime>("RokVracanja")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("VremeIzmene")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("VremeKreiranja")
                        .HasColumnType("datetime2");

                    b.Property<int>("ZaposleniId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("KnjigaId");

                    b.HasIndex("KorisnikId");

                    b.HasIndex("ZaposleniId");

                    b.ToTable("Pozajmice");
                });

            modelBuilder.Entity("Orfelin.Core.Models.Zaposleni", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Aktivan")
                        .HasColumnType("bit");

                    b.Property<string>("Ime")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Prezime")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Uloga")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("VremeIzmene")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("VremeKreiranja")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Zaposleni");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Aktivan = true,
                            Ime = "Admin",
                            PasswordHash = "$2a$11$zbcmZZTbkH7pXyyy7ehKYuUY9oOipOnWUpFS1qBEhpAm6kxoEDLCu",
                            Prezime = "Admin",
                            Uloga = "Rukovodilac",
                            Username = "admin",
                            VremeKreiranja = new DateTime(2026, 6, 11, 14, 34, 32, 636, DateTimeKind.Local).AddTicks(2301)
                        });
                });

            modelBuilder.Entity("Orfelin.Core.Models.Pozajmica", b =>
                {
                    b.HasOne("Orfelin.Core.Models.Knjiga", "Knjiga")
                        .WithMany()
                        .HasForeignKey("KnjigaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Orfelin.Core.Models.Korisnik", "Korisnik")
                        .WithMany()
                        .HasForeignKey("KorisnikId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Orfelin.Core.Models.Zaposleni", "Zaposleni")
                        .WithMany()
                        .HasForeignKey("ZaposleniId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Knjiga");

                    b.Navigation("Korisnik");

                    b.Navigation("Zaposleni");
                });
#pragma warning restore 612, 618
        }
    }
}
